const vocabularyData = [
  // --- JLPT N5 ---
  {
    id: "n5_1",
    kanji: "日本語",
    kana: "にほんご",
    romaji: "nihongo",
    vietnamese: "Tiếng Nhật",
    example: "日本語を勉強しています。",
    example_meaning: "Tôi đang học tiếng Nhật.",
    level: "N5",
    category: "Chung"
  },
  {
    id: "n5_2",
    kanji: "先生",
    kana: "せんせい",
    romaji: "sensei",
    vietnamese: "Thầy cô giáo",
    example: "日本語の先生はとても親切です。",
    example_meaning: "Giáo viên tiếng Nhật rất thân thiện.",
    level: "N5",
    category: "Con người"
  },
  {
    id: "n5_3",
    kanji: "学生",
    kana: "がくせい",
    romaji: "gakusei",
    vietnamese: "Học sinh, Sinh viên",
    example: "私はハノイ大学の学生です。",
    example_meaning: "Tôi là sinh viên trường Đại học Hà Nội.",
    level: "N5",
    category: "Con người"
  },
  {
    id: "n5_4",
    kanji: "友達",
    kana: "ともだち",
    romaji: "tomodachi",
    vietnamese: "Bạn bè",
    example: "週末に友達と遊びました。",
    example_meaning: "Tôi đã đi chơi với bạn bè vào cuối tuần.",
    level: "N5",
    category: "Con người"
  },
  {
    id: "n5_5",
    kanji: "食べる",
    kana: "たべる",
    romaji: "taberu",
    vietnamese: "Ăn",
    example: "朝ご飯にパンを食べます。",
    example_meaning: "Tôi ăn bánh mì vào bữa sáng.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_6",
    kanji: "飲む",
    kana: "のむ",
    romaji: "nomu",
    vietnamese: "Uống",
    example: "毎朝、お茶を飲みます。",
    example_meaning: "Mỗi sáng tôi đều uống trà.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_7",
    kanji: "行く",
    kana: "いく",
    romaji: "iku",
    vietnamese: "Đi",
    example: "明日、スーパーに行きます。",
    example_meaning: "Ngày mai tôi sẽ đi siêu thị.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_8",
    kanji: "本",
    kana: "ほん",
    romaji: "hon",
    vietnamese: "Sách",
    example: "図書館で本を借りました。",
    example_meaning: "Tôi đã mượn sách ở thư viện.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_9",
    kanji: "車",
    kana: "くるま",
    romaji: "kuruma",
    vietnamese: "Xe ô tô",
    example: "新しい車を買いたいです。",
    example_meaning: "Tôi muốn mua một chiếc xe ô tô mới.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_10",
    kanji: "水",
    kana: "みず",
    romaji: "mizu",
    vietnamese: "Nước",
    example: "冷たい水を一杯ください。",
    example_meaning: "Cho tôi xin một ly nước lạnh.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_11",
    kanji: "電話",
    kana: "でんわ",
    romaji: "denwa",
    vietnamese: "Điện thoại",
    example: "友達から電話がありました。",
    example_meaning: "Đã có cuộc điện thoại gọi đến từ bạn tôi.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_12",
    kanji: "家族",
    kana: "かぞく",
    romaji: "kazoku",
    vietnamese: "Gia đình",
    example: "私の家族は４人です。",
    example_meaning: "Gia đình tôi có 4 người.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_13",
    kanji: "美味しい",
    kana: "おいしい",
    romaji: "oishii",
    vietnamese: "Ngon (món ăn)",
    example: "この寿司はとても美味しいです。",
    example_meaning: "Món sushi này rất ngon.",
    level: "N5",
    category: "Tính từ"
  },
  {
    id: "n5_14",
    kanji: "大きい",
    kana: "おおきい",
    romaji: "ookii",
    vietnamese: "To, Lớn",
    example: "あの公園はとても大きいです。",
    example_meaning: "Công viên kia rất lớn.",
    level: "N5",
    category: "Tính từ"
  },
  {
    id: "n5_15",
    kanji: "時計",
    kana: "とけい",
    romaji: "tokei",
    vietnamese: "Đồng hồ",
    example: "新しい時計を買いました。",
    example_meaning: "Tôi đã mua một chiếc đồng hồ mới.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_16",
    kanji: "来る",
    kana: "くる",
    romaji: "kuru",
    vietnamese: "Đến",
    example: "あした、私のうちへ来てください。",
    example_meaning: "Ngày mai hãy đến nhà tôi nhé.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_17",
    kanji: "勉強",
    kana: "べんきょう",
    romaji: "benkyou",
    vietnamese: "Học tập",
    example: "毎日、日本語を３時間勉強します。",
    example_meaning: "Mỗi ngày tôi học tiếng Nhật 3 tiếng.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_18",
    kanji: "手紙",
    kana: "てがみ",
    romaji: "tegami",
    vietnamese: "Bức thư",
    example: "家族に手紙を書きました。",
    example_meaning: "Tôi đã viết thư cho gia đình.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_19",
    kanji: "空港",
    kana: "くうこう",
    romaji: "kuukou",
    vietnamese: "Sân bay",
    example: "成田空港へ友達を迎えに行きます。",
    example_meaning: "Tôi đi đón bạn ở sân bay Narita.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_20",
    kanji: "暑い",
    kana: "あつい",
    romaji: "atsui",
    vietnamese: "Nóng (thời tiết)",
    example: "今日はとても暑いですね。",
    example_meaning: "Hôm nay trời rất nóng nhỉ.",
    level: "N5",
    category: "Tính từ"
  },
  {
    id: "n5_21",
    kanji: "家",
    kana: "いえ",
    romaji: "ie",
    vietnamese: "Nhà",
    example: "私の家は駅の近くにあります。",
    example_meaning: "Nhà của tôi ở gần nhà ga.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_22",
    kanji: "学校",
    kana: "がっこう",
    romaji: "gakkou",
    vietnamese: "Trường học",
    example: "自転車で学校へ行きます。",
    example_meaning: "Tôi đi học bằng xe đạp.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_23",
    kanji: "教室",
    kana: "きょうしつ",
    romaji: "kyoushitsu",
    vietnamese: "Phòng học",
    example: "教室で日本語を勉強します。",
    example_meaning: "Học tiếng Nhật trong phòng học.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_24",
    kanji: "部屋",
    kana: "へや",
    romaji: "heya",
    vietnamese: "Căn phòng",
    example: "この部屋は明るくて広いです。",
    example_meaning: "Căn phòng này sáng sủa và rộng rãi.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_25",
    kanji: "食堂",
    kana: "しょくどう",
    romaji: "shokudou",
    vietnamese: "Nhà ăn",
    example: "大学の食堂で昼ご飯を食べます。",
    example_meaning: "Tôi ăn trưa ở nhà ăn của trường đại học.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_26",
    kanji: "靴",
    kana: "くつ",
    romaji: "kutsu",
    vietnamese: "Giày",
    example: "新しい黒い靴を買いました。",
    example_meaning: "Tôi đã mua một đôi giày màu đen mới.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_27",
    kanji: "傘",
    kana: "かさ",
    romaji: "kasa",
    vietnamese: "Dù, Ô",
    example: "雨が降っているので傘をさします。",
    example_meaning: "Trời đang mưa nên tôi che ô.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_28",
    kanji: "新聞",
    kana: "しんぶん",
    romaji: "shinbun",
    vietnamese: "Tờ báo",
    example: "毎朝、新聞を読みます。",
    example_meaning: "Mỗi sáng tôi đều đọc báo.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_29",
    kanji: "辞書",
    kana: "じしょ",
    romaji: "jisho",
    vietnamese: "Từ điển",
    example: "言葉の意味を辞書で調べます。",
    example_meaning: "Tôi tra ý nghĩa từ vựng bằng từ điển.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_30",
    kanji: "お金",
    kana: "おかね",
    romaji: "okane",
    vietnamese: "Tiền bạc",
    example: "財布にお金がありません。",
    example_meaning: "Trong ví tôi không có tiền.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_31",
    kanji: "切符",
    kana: "きっぷ",
    romaji: "kippu",
    vietnamese: "Vé (tàu, xe)",
    example: "電車の切符を買いました。",
    example_meaning: "Tôi đã mua vé tàu điện.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_32",
    kanji: "山",
    kana: "やま",
    romaji: "yama",
    vietnamese: "Núi",
    example: "富士山は日本で一番高い山です。",
    example_meaning: "Núi Phú Sĩ là ngọn núi cao nhất Nhật Bản.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_33",
    kanji: "川",
    kana: "かわ",
    romaji: "kawa",
    vietnamese: "Sông",
    example: "川で魚を釣りました。",
    example_meaning: "Tôi đã câu cá ở sông.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_34",
    kanji: "海",
    kana: "うみ",
    romaji: "umi",
    vietnamese: "Biển",
    example: "夏休みに海へ行きたいです。",
    example_meaning: "Tôi muốn đi biển vào kỳ nghỉ hè.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_35",
    kanji: "空",
    kana: "そら",
    romaji: "sora",
    vietnamese: "Bầu trời",
    example: "今日の空はとても青いです。",
    example_meaning: "Bầu trời hôm nay rất xanh.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_36",
    kanji: "天気",
    kana: "てんき",
    romaji: "tenki",
    vietnamese: "Thời tiết",
    example: "明日の天気はどうですか。",
    example_meaning: "Thời tiết ngày mai thế nào?",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_37",
    kanji: "雨",
    kana: "あめ",
    romaji: "ame",
    vietnamese: "Mưa",
    example: "午後から雨が降るでしょう。",
    example_meaning: "Có lẽ trời sẽ mưa từ buổi chiều.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_38",
    kanji: "雪",
    kana: "ゆき",
    romaji: "yuki",
    vietnamese: "Tuyết",
    example: "冬には雪がたくさん降ります。",
    example_meaning: "Tuyết rơi rất nhiều vào mùa đông.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_39",
    kanji: "風",
    kana: "かぜ",
    romaji: "kaze",
    vietnamese: "Gió",
    example: "今日は強い風が吹いています。",
    example_meaning: "Hôm nay trời thổi gió mạnh.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_40",
    kanji: "花",
    kana: "はな",
    romaji: "hana",
    vietnamese: "Hoa",
    example: "庭に綺麗な花が咲きました。",
    example_meaning: "Hoa đẹp đã nở trong vườn.",
    level: "N5",
    category: "Tự nhiên"
  },
  {
    id: "n5_41",
    kanji: "犬",
    kana: "いぬ",
    romaji: "inu",
    vietnamese: "Con chó",
    example: "私は白い犬を飼っています。",
    example_meaning: "Tôi đang nuôi một chú chó màu trắng.",
    level: "N5",
    category: "Động vật"
  },
  {
    id: "n5_42",
    kanji: "猫",
    kana: "ねこ",
    romaji: "neko",
    vietnamese: "Con mèo",
    example: "あの黒い猫はとても可愛いです。",
    example_meaning: "Chú mèo đen kia rất đáng yêu.",
    level: "N5",
    category: "Động vật"
  },
  {
    id: "n5_43",
    kanji: "魚",
    kana: "さかな",
    romaji: "sakana",
    vietnamese: "Con cá",
    example: "晩ご飯に魚の料理を食べました。",
    example_meaning: "Tôi đã ăn món cá vào bữa tối.",
    level: "N5",
    category: "Động vật"
  },
  {
    id: "n5_44",
    kanji: "鳥",
    kana: "とり",
    romaji: "tori",
    vietnamese: "Con chim",
    example: "空をたくさんの鳥が飛んでいます。",
    example_meaning: "Rất nhiều chim đang bay trên bầu trời.",
    level: "N5",
    category: "Động vật"
  },
  {
    id: "n5_45",
    kanji: "肉",
    kana: "にく",
    romaji: "niku",
    vietnamese: "Thịt",
    example: "牛肉と豚肉、どちらが好きですか。",
    example_meaning: "Thịt bò và thịt heo, bạn thích loại nào hơn?",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_46",
    kanji: "卵",
    kana: "たまご",
    romaji: "tamago",
    vietnamese: "Trứng",
    example: "朝ご飯に卵焼きを作りました。",
    example_meaning: "Tôi đã làm món trứng cuộn vào bữa sáng.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_47",
    kanji: "朝",
    kana: "あさ",
    romaji: "asa",
    vietnamese: "Buổi sáng",
    example: "朝早く起きて散歩します。",
    example_meaning: "Thức dậy sớm vào buổi sáng để đi dạo.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_48",
    kanji: "昼",
    kana: "ひる",
    romaji: "hiru",
    vietnamese: "Buổi trưa",
    example: "お昼休みに友達と話します。",
    example_meaning: "Nói chuyện với bạn bè vào giờ nghỉ trưa.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_49",
    kanji: "夜",
    kana: "よる",
    romaji: "yoru",
    vietnamese: "Buổi tối, Đêm",
    example: "夜は静かに本を読みます。",
    example_meaning: "Ban đêm tôi đọc sách một cách yên tĩnh.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_50",
    kanji: "今日",
    kana: "きょう",
    romaji: "kyou",
    vietnamese: "Hôm nay",
    example: "今日は天気がとても良いです。",
    example_meaning: "Thời tiết hôm nay rất tốt.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_51",
    kanji: "明日",
    kana: "あした",
    romaji: "ashita",
    vietnamese: "Ngày mai",
    example: "明日は日本語のテストがあります。",
    example_meaning: "Ngày mai có bài kiểm tra tiếng Nhật.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_52",
    kanji: "昨日",
    kana: "きのう",
    romaji: "kinou",
    vietnamese: "Hôm qua",
    example: "昨日は一日中雨が降っていました。",
    example_meaning: "Hôm qua trời mưa suốt cả ngày.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_53",
    kanji: "毎週",
    kana: "まいしゅう",
    romaji: "maishu",
    vietnamese: "Mỗi tuần",
    example: "毎週土曜日にテニスをします。",
    example_meaning: "Tôi chơi tennis vào mỗi thứ Bảy hàng tuần.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_54",
    kanji: "来月",
    kana: "らいげつ",
    romaji: "raigetsu",
    vietnamese: "Tháng sau",
    example: "来月、日本へ行く予定です。",
    example_meaning: "Tháng sau tôi có kế hoạch đi Nhật.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_55",
    kanji: "今年",
    kana: "ことし",
    romaji: "kotoshi",
    vietnamese: "Năm nay",
    example: "今年は日本語のN5に合格したいです。",
    example_meaning: "Năm nay tôi muốn thi đỗ JLPT N5.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_56",
    kanji: "来年",
    kana: "らいねん",
    romaji: "rainen",
    vietnamese: "Năm sau",
    example: "来年は大学を卒業します。",
    example_meaning: "Năm sau tôi tốt nghiệp đại học.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_57",
    kanji: "時間",
    kana: "じかん",
    romaji: "jikan",
    vietnamese: "Thời gian, Tiếng đồng hồ",
    example: "勉強の時間が足りません。",
    example_meaning: "Không đủ thời gian để học bài.",
    level: "N5",
    category: "Thời gian"
  },
  {
    id: "n5_58",
    kanji: "英語",
    kana: "えいご",
    romaji: "eigo",
    vietnamese: "Tiếng Anh",
    example: "英語を話すことができますか。",
    example_meaning: "Bạn có thể nói tiếng Anh không?",
    level: "N5",
    category: "Chung"
  },
  {
    id: "n5_59",
    kanji: "国",
    kana: "くに",
    romaji: "kuni",
    vietnamese: "Đất nước, Quốc gia",
    example: "あなたの国はどちらですか。",
    example_meaning: "Đất nước của bạn ở đâu vậy?",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_60",
    kanji: "駅",
    kana: "えき",
    romaji: "eki",
    vietnamese: "Nhà ga",
    example: "駅の改札口で待ち合わせましょう。",
    example_meaning: "Chúng ta hãy hẹn gặp nhau ở cổng soát vé nhà ga.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_61",
    kanji: "銀行",
    kana: "ぎんこう",
    romaji: "ginkou",
    vietnamese: "Ngân hàng",
    example: "銀行でお金を下ろします。",
    example_meaning: "Tôi rút tiền tại ngân hàng.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_62",
    kanji: "病院",
    kana: "びょういん",
    romaji: "byouin",
    vietnamese: "Bệnh viện",
    example: "風邪をひいたので病院へ行きます。",
    example_meaning: "Vì bị cảm nên tôi đi bệnh viện.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_63",
    kanji: "公園",
    kana: "こうえん",
    romaji: "kouen",
    vietnamese: "Công viên",
    example: "公園で子供たちが遊んでいます。",
    example_meaning: "Trẻ em đang chơi đùa ở công viên.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_64",
    kanji: "店",
    kana: "みせ",
    romaji: "mise",
    vietnamese: "Cửa hàng, Tiệm",
    example: "この店はいつも混んでいます。",
    example_meaning: "Cửa hàng này lúc nào cũng đông đúc.",
    level: "N5",
    category: "Địa điểm"
  },
  {
    id: "n5_65",
    kanji: "映画",
    kana: "えいが",
    romaji: "eiga",
    vietnamese: "Phim ảnh",
    example: "昨日、友達と映画を見ました。",
    example_meaning: "Hôm qua tôi đã xem phim cùng bạn bè.",
    level: "N5",
    category: "Giải trí"
  },
  {
    id: "n5_66",
    kanji: "音楽",
    kana: "おんがく",
    romaji: "ongaku",
    vietnamese: "Âm nhạc",
    example: "料理をしながら音楽を聞きます。",
    example_meaning: "Vừa nấu ăn tôi vừa nghe nhạc.",
    level: "N5",
    category: "Giải trí"
  },
  {
    id: "n5_67",
    kanji: "写真",
    kana: "しゃしん",
    romaji: "shashin",
    vietnamese: "Bức ảnh",
    example: "綺麗な景色を写真に撮りました。",
    example_meaning: "Tôi đã chụp ảnh phong cảnh đẹp.",
    level: "N5",
    category: "Giải trí"
  },
  {
    id: "n5_68",
    kanji: "手",
    kana: "て",
    romaji: "te",
    vietnamese: "Bàn tay",
    example: "ご飯を食べる前に手を洗います。",
    example_meaning: "Rửa tay trước khi ăn cơm.",
    level: "N5",
    category: "Cơ thể"
  },
  {
    id: "n5_69",
    kanji: "足",
    kana: "あし",
    romaji: "ashi",
    vietnamese: "Bàn chân, Cái chân",
    example: "階段から落ちて足を怪我しました。",
    example_meaning: "Ngã cầu thang nên tôi bị chấn thương ở chân.",
    level: "N5",
    category: "Cơ thể"
  },
  {
    id: "n5_70",
    kanji: "目",
    kana: "め",
    romaji: "me",
    vietnamese: "Mắt",
    example: "パソコンを使いすぎて目が疲れました。",
    example_meaning: "Sử dụng máy tính quá nhiều nên mỏi mắt.",
    level: "N5",
    category: "Cơ thể"
  },
  {
    id: "n5_71",
    kanji: "耳",
    kana: "みみ",
    romaji: "mimi",
    vietnamese: "Tai",
    example: "耳が痛いのでイヤホンを外します。",
    example_meaning: "Đau tai nên tôi bỏ tai nghe ra.",
    level: "N5",
    category: "Cơ thể"
  },
  {
    id: "n5_72",
    kanji: "口",
    kana: "くち",
    romaji: "kuchi",
    vietnamese: "Miệng",
    example: "口を大きく開けて発音してください。",
    example_meaning: "Hãy mở to miệng và phát âm nhé.",
    level: "N5",
    category: "Cơ thể"
  },
  {
    id: "n5_73",
    kanji: "体",
    kana: "からだ",
    romaji: "karada",
    vietnamese: "Cơ thể",
    example: "健康のために体に良い食事をします。",
    example_meaning: "Ăn thức ăn tốt cho cơ thể vì sức khỏe.",
    level: "N5",
    category: "Cơ thể"
  },
  {
    id: "n5_74",
    kanji: "男",
    kana: "おとこ",
    romaji: "otoko",
    vietnamese: "Nam giới, Đàn ông",
    example: "あの男の人は英語の先生です。",
    example_meaning: "Người đàn ông kia là giáo viên tiếng Anh.",
    level: "N5",
    category: "Con người"
  },
  {
    id: "n5_75",
    kanji: "女",
    kana: "おんな",
    romaji: "onna",
    vietnamese: "Nữ giới, Phụ nữ",
    example: "あそこに女の人が立っています。",
    example_meaning: "Có một người phụ nữ đang đứng ở đằng kia.",
    level: "N5",
    category: "Con người"
  },
  {
    id: "n5_76",
    kanji: "子供",
    kana: "こども",
    romaji: "kodomo",
    vietnamese: "Trẻ em, Con cái",
    example: "子供たちが庭で遊んでいます。",
    example_meaning: "Trẻ em đang chơi trong vườn.",
    level: "N5",
    category: "Con người"
  },
  {
    id: "n5_77",
    kanji: "父",
    kana: "ちち",
    romaji: "chichi",
    vietnamese: "Bố (của mình)",
    example: "私の父は銀行で働いています。",
    example_meaning: "Bố tôi đang làm việc tại ngân hàng.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_78",
    kanji: "母",
    kana: "はは",
    romaji: "haha",
    vietnamese: "Mẹ (của mình)",
    example: "私の母は料理がとても上手です。",
    example_meaning: "Mẹ tôi nấu ăn rất giỏi.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_79",
    kanji: "兄",
    kana: "あに",
    romaji: "ani",
    vietnamese: "Anh trai (của mình)",
    example: "兄は東京の大学に通っています。",
    example_meaning: "Anh trai tôi đang học đại học ở Tokyo.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_80",
    kanji: "姉",
    kana: "あね",
    romaji: "ane",
    vietnamese: "Chị gái (của mình)",
    example: "私の姉はすでに結婚しています。",
    example_meaning: "Chị gái tôi đã kết hôn rồi.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_81",
    kanji: "弟",
    kana: "おとうと",
    romaji: "otouto",
    vietnamese: "Em trai (của mình)",
    example: "弟は高校生で、サッカー部です。",
    example_meaning: "Em trai tôi là học sinh cấp 3, tham gia CLB bóng đá.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_82",
    kanji: "妹",
    kana: "いもうと",
    romaji: "imouto",
    vietnamese: "Em gái (của mình)",
    example: "私の妹は今年、中学生になります。",
    example_meaning: "Em gái tôi năm nay sẽ lên học cấp 2.",
    level: "N5",
    category: "Gia đình"
  },
  {
    id: "n5_83",
    kanji: "服",
    kana: "ふく",
    romaji: "fuku",
    vietnamese: "Quần áo",
    example: "新しい服を買いに出かけます。",
    example_meaning: "Tôi ra ngoài để mua quần áo mới.",
    level: "N5",
    category: "Đồ vật"
  },
  {
    id: "n5_84",
    kanji: "朝ご飯",
    kana: "あさごはん",
    romaji: "asagohan",
    vietnamese: "Bữa ăn sáng",
    example: "朝ご飯はいつもパンとコーヒーです。",
    example_meaning: "Bữa sáng của tôi luôn là bánh mì và cà phê.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_85",
    kanji: "昼ご飯",
    kana: "ひるごはん",
    romaji: "hirugohan",
    vietnamese: "Bữa ăn trưa",
    example: "昼ご飯はコンビニの弁当を食べました。",
    example_meaning: "Tôi đã ăn cơm hộp tiện lợi vào bữa trưa.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_86",
    kanji: "晩ご飯",
    kana: "ばんごはん",
    romaji: "bangohan",
    vietnamese: "Bữa ăn tối",
    example: "家族と一緒に晩ご飯を食べます。",
    example_meaning: "Tôi ăn tối cùng với gia đình.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_87",
    kanji: "お茶",
    kana: "おちゃ",
    romaji: "ocha",
    vietnamese: "Nước trà",
    example: "ご飯を食べた後でお茶を飲みます。",
    example_meaning: "Uống trà sau khi ăn cơm xong.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_88",
    kanji: "牛乳",
    kana: "ぎゅうにゅう",
    romaji: "gyuunyuu",
    vietnamese: "Sữa bò",
    example: "毎朝、牛乳を一杯飲みます。",
    example_meaning: "Mỗi sáng tôi đều uống một ly sữa.",
    level: "N5",
    category: "Ăn uống"
  },
  {
    id: "n5_89",
    kanji: "買う",
    kana: "かう",
    romaji: "kau",
    vietnamese: "Mua sắm, Mua",
    example: "デパートで服を買いました。",
    example_meaning: "Tôi đã mua quần áo ở trung tâm thương mại.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_90",
    kanji: "売る",
    kana: "うる",
    romaji: "uru",
    vietnamese: "Bán hàng, Bán",
    example: "古い車を売ることにしました。",
    example_meaning: "Tôi quyết định bán chiếc xe cũ đi.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_91",
    kanji: "書く",
    kana: "かく",
    romaji: "kaku",
    vietnamese: "Viết chữ, Viết",
    example: "ノートに言葉の意味を書きます。",
    example_meaning: "Viết nghĩa của từ vựng vào vở.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_92",
    kanji: "読む",
    kana: "よむ",
    romaji: "yomu",
    vietnamese: "Đọc sách, Đọc",
    example: "毎日、日本語の本を読みます。",
    example_meaning: "Mỗi ngày tôi đều đọc sách tiếng Nhật.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_93",
    kanji: "聞く",
    kana: "きく",
    romaji: "kiku",
    vietnamese: "Nghe, Hỏi",
    example: "先生の話をよく聞いてください。",
    example_meaning: "Hãy chú ý lắng nghe lời của giáo viên.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_94",
    kanji: "話す",
    kana: "はなす",
    romaji: "hanasu",
    vietnamese: "Nói chuyện, Phát biểu",
    example: "友達と日本語で話します。",
    example_meaning: "Tôi nói chuyện với bạn bè bằng tiếng Nhật.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_95",
    kanji: "見る",
    kana: "みる",
    romaji: "miru",
    vietnamese: "Nhìn, Xem, Quan sát",
    example: "夜遅くテレビを見ます。",
    example_meaning: "Tôi xem ti vi vào đêm muộn.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_96",
    kanji: "待つ",
    kana: "まつ",
    romaji: "matsu",
    vietnamese: "Đợi, Chờ đợi",
    example: "駅の前でバスを待ちます。",
    example_meaning: "Chờ xe buýt ở trước nhà ga.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_97",
    kanji: "持つ",
    kana: "もつ",
    romaji: "motsu",
    vietnamese: "Cầm, Nắm, Mang theo",
    example: "カバンを持っていただけますか。",
    example_meaning: "Bạn cầm hộ tôi chiếc cặp xách được không?",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_98",
    kanji: "作る",
    kana: "つくる",
    romaji: "tsukuru",
    vietnamese: "Chế tạo, Nấu ăn, Làm",
    example: "今夜の晩ご飯は私が作ります。",
    example_meaning: "Tôi sẽ làm bữa tối cho đêm nay.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_99",
    kanji: "使う",
    kana: "つかう",
    romaji: "tsukau",
    vietnamese: "Sử dụng, Tiêu dùng",
    example: "勉強のときに辞書を使います。",
    example_meaning: "Sử dụng từ điển trong khi học tập.",
    level: "N5",
    category: "Hành động"
  },
  {
    id: "n5_100",
    kanji: "遊ぶ",
    kana: "あそぶ",
    romaji: "asobu",
    vietnamese: "Chơi, Vui chơi",
    example: "週末に公園で友達と遊びます。",
    example_meaning: "Cuối tuần tôi đi chơi với bạn ở công viên.",
    level: "N5",
    category: "Hành động"
  },

  // --- JLPT N4 ---
  {
    id: "n4_1",
    kanji: "準備",
    kana: "じゅんび",
    romaji: "junbi",
    vietnamese: "Chuẩn bị",
    example: "旅行의 準備를 합니다.",
    example_meaning: "Tôi chuẩn bị cho chuyến đi du lịch.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_2",
    kanji: "運転",
    kana: "うんてん",
    romaji: "unten",
    vietnamese: "Lái xe",
    example: "車の運転ができますか。",
    example_meaning: "Bạn có biết lái xe ô tô không?",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_3",
    kanji: "世界",
    kana: "せかい",
    romaji: "sekai",
    vietnamese: "Thế giới",
    example: "世界中を旅行したいです。",
    example_meaning: "Tôi muốn đi du lịch vòng quanh thế giới.",
    level: "N4",
    category: "Địa điểm"
  },
  {
    id: "n4_4",
    kanji: "簡単",
    kana: "かんたん",
    romaji: "kantan",
    vietnamese: "Đơn giản, Dễ dàng",
    example: "この試験は簡単でした。",
    example_meaning: "Kỳ thi này đã rất dễ.",
    level: "N4",
    category: "Tính từ"
  },
  {
    id: "n4_5",
    kanji: "説明",
    kana: "せつめい",
    romaji: "setsumei",
    vietnamese: "Giải thích",
    example: "使い方を詳しく説明します。",
    example_meaning: "Tôi sẽ giải thích chi tiết cách sử dụng.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_6",
    kanji: "約束",
    kana: "やくそく",
    romaji: "yakusoku",
    vietnamese: "Hẹn, Hứa hẹn",
    example: "友達と映画に行く約束があります。",
    example_meaning: "Tôi có hẹn đi xem phim với bạn bè.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_7",
    kanji: "便利",
    kana: "べんり",
    romaji: "benri",
    vietnamese: "Tiện lợi",
    example: "スマホはとても便利です。",
    example_meaning: "Điện thoại thông minh rất tiện lợi.",
    level: "N4",
    category: "Tính từ"
  },
  {
    id: "n4_8",
    kanji: "辞める",
    kana: "やめる",
    romaji: "yameru",
    vietnamese: "Từ bỏ, Nghỉ (việc)",
    example: "来月、会社を辞めます。",
    example_meaning: "Tháng sau tôi sẽ nghỉ việc ở công ty.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_9",
    kanji: "注意",
    kana: "ちゅうい",
    romaji: "chuui",
    vietnamese: "Chú ý, Nhắc nhở",
    example: "車に注意してください。",
    example_meaning: "Hãy chú ý xe cộ nhé.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_10",
    kanji: "紹介",
    kana: "しょうかい",
    romaji: "shoukai",
    vietnamese: "Giới thiệu",
    example: "自己紹介をしてください。",
    example_meaning: "Xin mời hãy tự giới thiệu bản thân.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_11",
    kanji: "試合",
    kana: "しあい",
    romaji: "shiai",
    vietnamese: "Trận đấu",
    example: "明日のサッカーの試合を見に行きます。",
    example_meaning: "Tôi sẽ đi xem trận đấu bóng đá ngày mai.",
    level: "N4",
    category: "Giải trí"
  },
  {
    id: "n4_12",
    kanji: "安全",
    kana: "あんぜん",
    romaji: "anzen",
    vietnamese: "An toàn",
    example: "この町は夜でも安全です。",
    example_meaning: "Thành phố này ban đêm cũng rất an toàn.",
    level: "N4",
    category: "Tính từ"
  },
  {
    id: "n4_13",
    kanji: "調べる",
    kana: "しらべる",
    romaji: "shiraberu",
    vietnamese: "Điều tra, Tìm hiểu",
    example: "辞書で言葉の意味を調べます。",
    example_meaning: "Tôi tìm ý nghĩa của từ vựng bằng từ điển.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_14",
    kanji: "連絡",
    kana: "れんらく",
    romaji: "renraku",
    vietnamese: "Liên lạc",
    example: "遅れるときは電話で連絡してください。",
    example_meaning: "Khi bị trễ hãy liên lạc bằng điện thoại nhé.",
    level: "N4",
    category: "Hành động"
  },
  {
    id: "n4_15",
    kanji: "危険",
    kana: "きけん",
    romaji: "kiken",
    vietnamese: "Nguy hiểm",
    example: "あそこは車が多くて危険です。",
    example_meaning: "Chỗ kia nhiều xe cộ nên rất nguy hiểm.",
    level: "N4",
    category: "Tính từ"
  },

  // --- JLPT N3 ---
  {
    id: "n3_1",
    kanji: "解決",
    kana: "かいけつ",
    romaji: "kaiketsu",
    vietnamese: "Giải quyết",
    example: "この問題は無事に解決しました。",
    example_meaning: "Vấn đề này đã được giải quyết ổn thỏa.",
    level: "N3",
    category: "Hành động"
  },
  {
    id: "n3_2",
    kanji: "経験",
    kana: "けいけん",
    romaji: "keiken",
    vietnamese: "Kinh nghiệm",
    example: "日本で仕事の経験があります。",
    example_meaning: "Tôi có kinh nghiệm làm việc ở Nhật.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_3",
    kanji: "技術",
    kana: "ぎじゅつ",
    romaji: "gijutsu",
    vietnamese: "Kỹ thuật, Công nghệ",
    example: "日本のIT技術を学びたいです。",
    example_meaning: "Tôi muốn học hỏi công nghệ CNTT của Nhật Bản.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_4",
    kanji: "環境",
    kana: "かんきょう",
    romaji: "kankyou",
    vietnamese: "Môi trường",
    example: "自然環境を守ることが大切です。",
    example_meaning: "Bảo vệ môi trường tự nhiên là rất quan trọng.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_5",
    kanji: "緊張",
    kana: "きんちょう",
    romaji: "kinchou",
    vietnamese: "Căng thẳng, Hồi hộp",
    example: "面接の前はとても緊張しました。",
    example_meaning: "Tôi đã rất hồi hộp trước buổi phỏng vấn.",
    level: "N3",
    category: "Cảm xúc"
  },
  {
    id: "n3_6",
    kanji: "複雑",
    kana: "ふくざつ",
    romaji: "fukuzatsu",
    vietnamese: "Phức tạp",
    example: "この機械の使い方は複雑です。",
    example_meaning: "Cách sử dụng máy này rất phức tạp.",
    level: "N3",
    category: "Tính từ"
  },
  {
    id: "n3_7",
    kanji: "期待",
    kana: "きたい",
    romaji: "kitai",
    vietnamese: "Kỳ vọng, Mong đợi",
    example: "両親の期待に応えたいです。",
    example_meaning: "Tôi muốn đáp ứng kỳ vọng của bố mẹ.",
    level: "N3",
    category: "Cảm xúc"
  },
  {
    id: "n3_8",
    kanji: "習慣",
    kana: "しゅうかん",
    romaji: "shuukan",
    vietnamese: "Thói quen, Tập quán",
    example: "早寝早起きは良い習慣です。",
    example_meaning: "Ngủ sớm dậy sớm là một thói quen tốt.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_9",
    kanji: "絶対",
    kana: "ぜったい",
    romaji: "zettai",
    vietnamese: "Tuyệt đối, Chắc chắn",
    example: "約束は絶対に守ります。",
    example_meaning: "Tôi chắc chắn sẽ giữ lời hứa.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_10",
    kanji: "満足",
    kana: "まんぞく",
    romaji: "manzoku",
    vietnamese: "Thỏa mãn, Hài lòng",
    example: "今回の結果には満足しています。",
    example_meaning: "Tôi rất hài lòng với kết quả lần này.",
    level: "N3",
    category: "Cảm xúc"
  },
  {
    id: "n3_11",
    kanji: "開発",
    kana: "かいhatsu",
    romaji: "kaihatsu",
    vietnamese: "Phát triển (phần mềm/sản phẩm)",
    example: "新しいソフトウェアを開発しています。",
    example_meaning: "Chúng tôi đang phát triển một phần mềm mới.",
    level: "N3",
    category: "Công việc"
  },
  {
    id: "n3_12",
    kanji: "調査",
    kana: "ちょうさ",
    romaji: "chousa",
    vietnamese: "Điều tra, Khảo sát",
    example: "市場調査の結果を報告します。",
    example_meaning: "Tôi báo cáo kết quả khảo sát thị trường.",
    level: "N3",
    category: "Công việc"
  },
  {
    id: "n3_13",
    kanji: "影響",
    kana: "えいきょう",
    romaji: "eikyou",
    vietnamese: "Ảnh hưởng",
    example: "天候は農作物の収穫に影響します。",
    example_meaning: "Thời tiết ảnh hưởng đến thu hoạch nông sản.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_14",
    kanji: "集中",
    kana: "しゅうちゅう",
    romaji: "shuuchuu",
    vietnamese: "Tập trung",
    example: "勉強に集中することができません。",
    example_meaning: "Tôi không thể tập trung vào việc học.",
    level: "N3",
    category: "Chung"
  },
  {
    id: "n3_15",
    kanji: "回復",
    kana: "かいふく",
    romaji: "kaifuku",
    vietnamese: "Hồi phục",
    example: "病気から早く回復することを祈ります。",
    example_meaning: "Tôi cầu mong bạn nhanh chóng hồi phục khỏi bệnh.",
    level: "N3",
    category: "Chung"
  }
];

// Export to make it available via ES Modules or simple script tag
if (typeof module !== 'undefined' && module.exports) {
  module.exports = vocabularyData;
}
